### ISSUE TITLE
i keep getting this issue (SSV_OV) [FATAL ERROR] Exception in clbkLoadStateEx: ADI_MEDS.msh loading failed

### ISSUE THREAD

**Issue by rocketman572** [GLS-SSV/SSV#23]
![Screenshot 2024-09-02 115721](https://github.com/user-attachments/assets/de24df42-eedc-4b6d-bac4-052556150cd0)

**Comment by broadcastday** [comment]
Also getting this issue. 

000041.038: Added subsystem ODS.
000041.042: (AtlantisSubsystem) Create subsystem DeployedAssembly.
000041.090: Added subsystem DeployedAssembly.
000041.095: (AtlantisSubsystem) Create subsystem ElectronicsAssembly1.
000041.098: Added subsystem ElectronicsAssembly1.
000041.102: (AtlantisSubsystem) Create subsystem ElectronicsAssembly2.
000041.106: Added subsystem ElectronicsAssembly2.
000041.109: (AtlantisSubsystem) Create subsystem DragChute.
000041.138: Added subsystem DragChute.
000042.008: (SSV_OV) [FATAL ERROR] Exception in clbkLoadStateEx: ADI_MEDS.msh loading failed

**Comment by GLS-SSV** [comment]
SSV is build specifically for Orbiter 2016. The development versions of the new Orbiter, and previous versions, are not (yet) supported.
It seems this issue is caused by running SSV in a version of Orbiter other than 2016. Can you confirm that this is the case, and there are no issues when running SSV in Orbiter 2016?

Related: https://www.orbiter-forum.com/threads/i-keep-getting-this-issue.41925/

**Comment by broadcastday** [comment]
Yes, I'm using the Orbiter 2024 rc1. That explains it.
